### ISSUE TITLE
the “select” and “inbox” only work when there is an empty CheckBox in that note

### ISSUE THREAD

**Issue by wuzhen97** [702573N/Obsidian-Tasks-Timeline#18]
![image](https://user-images.githubusercontent.com/61906420/212600250-3c2582b1-55cc-4739-8d13-612bb0aa96ce.png)

![image](https://user-images.githubusercontent.com/61906420/212600263-e20fb6fa-c283-4328-8fed-4afabd22ee1f.png)

**Comment by 702573N** [comment]
Please download the latest version [1.1.5](https://github.com/702573N/Obsidian-Tasks-Timeline/archive/refs/heads/main.zip) to fixing the invisible Inbox problem!

The other thing mentioned works as programmed. Taskido tries to identify relevant notes by searching for notes with unfinished tasks. These are then offered for selection in the select box. Listing all the notes in the vault is out of the question due to the amount of notes. Alternatively, notes could be tagged, or a folder path could be specified using parameters. Do you have any ideas on how to handle this better?
