### ISSUE TITLE
Support grouping tasks based on All, To do, Overdue and Unplanned

### ISSUE THREAD

**Issue by wenlzhang** [702573N/Obsidian-Tasks-Timeline#21]
Currently, all tasks would show on the same column, and clicking one category, e.g., "To Do", would highlight all related tasks for today. It would be great if the tasks can be categorized as something like All, To Do, Overdue and Unplanned:

- For the group "All", it would list all tasks, including "To Do", "Overdue" and "Unplanned". Since "Overdue" tasks would be red by default, one can still distinguish different groups of tasks.
- For the group "To Do", it would not include "Overdue" or "Unplanned" tasks. It is similar for the groups "Overdue" and "Unplanned".
- One can set in options which group to focus on by default.

By grouping tasks like this, one can better see tasks in each group, instead of, for example, scrolling to the bottom of "Overdue" to see "To Do" tasks.

<img width="572" alt="Screenshot 2023-01-17 at 12 51 32" src="https://user-images.githubusercontent.com/44930227/212893495-84e2dae4-6c7d-4888-a0d6-93321cb94851.png">

**Comment by wenlzhang** [comment]
On the other hand, if one chooses not to display Overdue tasks on Today, the behaviour might be a little different.

**Comment by 702573N** [comment]
1. Everyone is free to use the script or not.

2. This script is not adapted to the usage behavior of individuals, but to the standard usage behavior of the majority.

3. You can choose between "focus" mode (`options: "focus"` = set by default) and "filter" mode (`options: "filter"`). On "focus" mode the selected tasks category is highlighted without hiding all other tasks. With "filter" mode you can hide all unwanted tasks except the following tasks...

    3.1. ToDo
         Shows all tasks which are to be done today (due today), as well as tasks which start today (start today), or are currently in progress (start before today and due after today).

    3.2. Overdue
         Shows only tasks that are overdue and therefore had to be done before today. Nothing else.

    3.3. Unplanned
         Shows tasks without assigned dates.

https://github.com/702573N/Obsidian-Tasks-Timeline#options

4. The "All" category isn't needed because you can see all tasks on today if no filter (ToDo, Overdue, Unplanned) is selected.
