### ISSUE TITLE
Check box [actually check the task from dataview]

### ISSUE THREAD

**Issue by dxcore35** [702573N/Obsidian-Tasks-Timeline#26]
It will be amazing to also check or uncheck the tasks in the view!

**Comment by 702573N** [comment]
You can check/uncheck tasks inside the timeline by clicking on the task icon. Unfortunately it's not possible (at that moment) to due this action without opening the note file, because I'm using the check task feature from the Task Plugin itself to handle the repeating task correctly without programming all repeating rules by self.
